import {
  GROUP_DO_POINTS,
  GROUP_DO,
  GROUP_DECIDE,
  GROUP_DELEGATE,
  GROUP_DELETE,
  GROUP_DECIDE_POINTS,
  GROUP_DELEGATE_POINTS,
  GROUP_DELETE_POINTS,
} from "./constants";
import type { GroupName } from "./types";

export const taskGroupPoints: Record<GroupName, number> = {
  [GROUP_DO]: GROUP_DO_POINTS,
  [GROUP_DECIDE]: GROUP_DECIDE_POINTS,
  [GROUP_DELEGATE]: GROUP_DELEGATE_POINTS,
  [GROUP_DELETE]: GROUP_DELETE_POINTS,
};
